
name: submit-cookie-to-download-kindle

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      csrfToken:
        description: 'amazon.cn  csrfToken'
        type: enviroment
        required: true
      domain:
        description: 'domain string such as cn,jp,com'
        type: enviroment
        required: true
      startindex:
        description: 'resume from 1'
        type: enviroment
        required: false
      downloadfiletype:
        description: 'choose either "PDOC" or "EBOK"'
        type: enviroment
        required: true
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run demo
      run: |
        python3 kindle_dummy.py
      env:
        csrfToken: ${{ github.event.inputs.csrfToken }}        
        domain: ${{ github.event.inputs.domain }}        
    # 配置git
    - name: Config git
      run: |
        git config --local user.email "ations@github.com"
        git config --local user.name "github"
        git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
    # 更新仓库
    - name: Update repo
      run: |
        git add .
        git commit -m "auto update kindle download"
        git pull
        git push -u origin main
      
